name: Integration Tests Dynamic
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
env: 
  GIT_CLONE_PROTECTION_ACTIVE: false
jobs:
  test:
    name: Integration Tests Dynamic
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore Cache Bazel output
        id: restore-cache-bazel-output
        uses: actions/cache/restore@v3
        env:
          cache-name: cache-bazel-output
        with:
          path: bazel-output-base
          key: ${{ runner.os }}-integration-dynamic-${{ env.cache-name }}

      - name: make bootstrap
        run: make bootstrap

      - name: make integration-dynamic
        run: make integration-dynamic

      - name: Save Cache Bazel output
        id: save-cache-bazel-output
        uses: actions/cache/save@v3
        if: always()
        env:
          cache-name: cache-bazel-output
        with:
          path: bazel-output-base
          key: ${{ steps.restore-cache-bazel-output.outputs.cache-primary-key }}
